# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Regression tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: # Keep these in ascending order for automagic with coverage
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        # Basic check for minimal deployed env requirements
        python -c "import pyttb"
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade coverage sphinx_rtd_theme
        pip install ".[dev]"
    - name: Run tests
      run: |
        coverage run --source pyttb -m pytest tests/
        coverage report
    - name: Add coveralls dependencies
      if: strategy.job-index == 0
      run: |
        python -m pip install --upgrade coveralls
    - name: Upload coverage to Coveralls
      if: strategy.job-index == 0
      uses: coverallsapp/github-action@v2
      #env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #run: |
      #  coveralls --service=github
